---
name: CI - Vérification HTML

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-html:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Vérification syntaxe HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .
